/*ALGORITMO: "funcao fatorial"
--AUTOR: ORTO GAMER¡
--DATA E HORA: 22 de Janeiro de 2023  |  03:20:13 */
inicio
	inteiro contador, fatorial
    escreva "digite o numero que deseja calcular O FATORIAL  "
    leia contador
    enquanto fatorial<=contador faca
    	fatorial<- contador*(contador-1)*(contador-2)*(CONTADOR-3)
    	fimenquanto
    	escreva "o fatorial do numero digitado é", fatorial
fimalgoritmo
    